import assert from "node:assert/strict";
import test from "node:test";
import { handleAdvancedComparisonRequest } from "./advanced-comparison-handler.ts";
const body={checkpoint:7,metrics:["reach"],cohorts:[
  {key:"A",label:"أ",range:{start:"2026-06-01",end:"2026-06-30"},track_ids:[1,1],partner_ids:[],idea_type_ids:[],media_types:[],participants:[]},
  {key:"B",label:"ب",range:{start:"2026-07-01",end:"2026-07-31"},track_ids:[],partner_ids:[],idea_type_ids:[],media_types:["REELS"],participants:[]},
]};
test("rejects cross-origin before authorization",async()=>{let calls=0;const result=await handleAdvancedComparisonRequest({expectedOrigin:"https://preview.example",origin:"https://evil.example",referer:null,secFetchSite:"cross-site",body,authorize:async()=>{calls++;return {ok:false,status:401,body:{error:"x",code:"E_AUTH"}};}});assert.equal(result.status,403);assert.equal(calls,0);});
test("normalizes and forwards through the authenticated RPC",async()=>{let captured:unknown;const result=await handleAdvancedComparisonRequest({expectedOrigin:"https://preview.example",origin:"https://preview.example",referer:null,secFetchSite:"same-origin",body,now:new Date("2026-09-23T12:00:00Z"),authorize:async()=>({ok:true,client:{rpc:async(name,args)=>{captured={name,args};return {data:{result_hash:"x"},error:null};}}})});assert.equal(result.status,200);assert.deepEqual(captured,{name:"admin_advanced_analytics_comparison",args:{p_request:{checkpoint:7,metrics:["reach"],cohorts:[{...body.cohorts[0],track_ids:[1]},{...body.cohorts[1]}],evaluated_at:"2026-09-23T12:00:00.000Z"}}});});
test("returns authorization and service errors without fallback writes",async()=>{const denied=await handleAdvancedComparisonRequest({expectedOrigin:"https://x",origin:"https://x",referer:null,secFetchSite:"same-origin",body,authorize:async()=>({ok:false,status:403,body:{error:"ممنوع",code:"E_FORBIDDEN"}})});assert.equal(denied.status,403);const failed=await handleAdvancedComparisonRequest({expectedOrigin:"https://x",origin:"https://x",referer:null,secFetchSite:"same-origin",body,authorize:async()=>({ok:true,client:{rpc:async()=>({data:null,error:{message:"db"}})}})});assert.equal(failed.status,503);});
