"use client";
import {useEffect,useMemo,useRef,useState}from"react";
import type{AdvancedCheckpoint,AdvancedCohort,AdvancedComparisonPayload,AdvancedMetric}from"@/lib/advanced-comparison";
import{advancedMetricLabels,advancedReelsWarning,timelineMetricRows}from"@/lib/advanced-comparison-view";
import type{InsightRange}from"@/lib/insights";import type{ComparisonResult}from"@/lib/analytics-comparison";import type{TeamMemberOption}from"@/lib/admin-create-item";import type{RoleName}from"@/lib/ui-data";
import{CohortEditor,type AdvancedComparisonOptions}from"./cohort-editor";import{ComparisonResultTable}from"./comparison-result-table";import{ComparisonEvidence}from"./comparison-evidence";import{ComparisonChart}from"./comparison-chart";import{MetricLineChart}from"./metric-line-chart";
import{AddToReportButton}from"./add-to-report-button";
type Props={range:InsightRange;currentUserId:string;roles:RoleName[];teamMembers:TeamMemberOption[];teamMembersLoadError:string|null};
type LoadState={kind:"idle"|"loading"}|{kind:"error";message:string}|{kind:"ready";payload:AdvancedComparisonPayload};
const requestedMetrics:AdvancedMetric[]=["reach","save_rate","share_rate","follow_rate","visit_rate","signal","item_count"];
function previous(range:InsightRange){const start=new Date(`${range.start}T00:00:00Z`);const end=new Date(`${range.end}T00:00:00Z`);const days=Math.floor((end.valueOf()-start.valueOf())/86400000)+1;const prevEnd=new Date(start);prevEnd.setUTCDate(prevEnd.getUTCDate()-1);const prevStart=new Date(prevEnd);prevStart.setUTCDate(prevStart.getUTCDate()-days+1);return{start:prevStart.toISOString().slice(0,10),end:prevEnd.toISOString().slice(0,10)};}
function make(key:"A"|"B",label:string,range:InsightRange):AdvancedCohort{return{key,label,range,track_ids:[],partner_ids:[],idea_type_ids:[],media_types:[],participants:[]};}
export function AdvancedComparison({range,currentUserId,roles,teamMembers,teamMembersLoadError}:Props){
  const[options,setOptions]=useState<AdvancedComparisonOptions|null>(null);const[optionsError,setOptionsError]=useState("");const[checkpoint,setCheckpoint]=useState<AdvancedCheckpoint>(7);const[cohorts,setCohorts]=useState<[AdvancedCohort,AdvancedCohort]>(()=>[make("A","الفترة السابقة",previous(range)),make("B","الفترة الحالية",range)]);const[selectedMetric,setSelectedMetric]=useState<AdvancedMetric>("reach");const[state,setState]=useState<LoadState>({kind:"idle"});const controllerRef=useRef<AbortController|null>(null);
  useEffect(()=>{const controller=new AbortController();fetch("/api/insights/compare?mode=options",{cache:"no-store",credentials:"same-origin",signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||"تعذر تحميل مرشحات المقارنة.");setOptions(body.options);}).catch(error=>{if(!controller.signal.aborted)setOptionsError(error instanceof Error?error.message:"تعذر تحميل مرشحات المقارنة.");});return()=>controller.abort();},[]);
  useEffect(()=>()=>controllerRef.current?.abort(),[]);
  function update(index:0|1,next:AdvancedCohort){setCohorts(current=>index===0?[next,current[1]]:[current[0],next]);}
  async function submit(event:React.FormEvent){event.preventDefault();controllerRef.current?.abort();const controller=new AbortController();controllerRef.current=controller;setState({kind:"loading"});try{const response=await fetch("/api/insights/compare/advanced",{method:"POST",cache:"no-store",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({checkpoint,metrics:requestedMetrics,cohorts}),signal:controller.signal});const body=await response.json();if(!response.ok)throw new Error(body.error||"تعذر حساب المقارنة المتقدمة.");setState({kind:"ready",payload:body});}catch(error){if(!controller.signal.aborted)setState({kind:"error",message:error instanceof Error?error.message:"تعذر حساب المقارنة المتقدمة."});}}
  const selected=state.kind==="ready"?state.payload.metrics.find(row=>row.metric===selectedMetric)??null:null;
  const chartRows=useMemo<ComparisonResult[]>(()=>{if(!selected||state.kind!=="ready")return[];const labels=Object.fromEntries(state.payload.cohorts.map(row=>[row.key,row.label]));const warning=advancedReelsWarning(selectedMetric,state.payload.evidence);return[{dimension_key:"A",dimension_name:labels.A??"A",participant_part:null,total_n:selected.a_eligible_n,measured_n:selected.a_measured_n,median_value:selected.cohort_a,is_thin:selected.a_measured_n>0&&selected.a_measured_n<4,has_partial_reels:warning},{dimension_key:"B",dimension_name:labels.B??"B",participant_part:null,total_n:selected.b_eligible_n,measured_n:selected.b_measured_n,median_value:selected.cohort_b,is_thin:selected.b_measured_n>0&&selected.b_measured_n<4,has_partial_reels:warning}];},[selected,selectedMetric,state]);
  const timeline=state.kind==="ready"?timelineMetricRows(state.payload.timeline,selectedMetric):[];const series=state.kind==="ready"?(["A","B"]as const).map(key=>({label:state.payload.cohorts.find(row=>row.key===key)?.label??key,points:timeline.filter(point=>point.cohort===key).map(point=>({x:`${point.month}-01`,y:point.value}))})):[];
  return <div className="stack advanced-comparison"><form className="stack" onSubmit={submit}><section className="card stack"><div className="advanced-comparison-heading"><div><h2>مقارنة مجموعتين مخصصتين</h2><p className="muted">مرشحات كل مجموعة مستقلة. جميع المقاييس تأتي من لقطة العمر نفسها.</p></div><label className="field advanced-checkpoint">عمر القياس<select className="input" value={checkpoint} onChange={event=>setCheckpoint(Number(event.target.value)as AdvancedCheckpoint)}><option value={1}>D1</option><option value={7}>D7</option><option value={30}>D30</option></select></label></div><p className="soft-banner">D{checkpoint} يعني لقطة مسجلة في يوم العمر المختار، ولا تُستخدم أقرب لقطة بديلة بصمت.</p></section>{optionsError?<p className="error">{optionsError}</p>:null}{!options&&!optionsError?<section className="card"><p>جارٍ تحميل المرشحات…</p></section>:null}{options?<div className="advanced-cohort-grid"><CohortEditor cohort={cohorts[0]} options={options} onChange={next=>update(0,next)}/><CohortEditor cohort={cohorts[1]} options={options} onChange={next=>update(1,next)}/></div>:null}<button className="button advanced-submit" type="submit" disabled={!options||state.kind==="loading"}>{state.kind==="loading"?"جارٍ الحساب…":"احسب المقارنة"}</button></form>
  {state.kind==="error"?<section className="card"><p className="error">{state.message}</p></section>:null}{state.kind==="ready"?<><section className="card stack advanced-results"><div className="insight-result-head"><div><h2>نتيجة المقارنة</h2><p className="muted">الفرق العددي هو B−A، دون اختيار فائز أو إصدار حكم.</p></div><AddToReportButton advanced={{title:`مقارنة ${state.payload.cohorts[0]?.label??"A"} و${state.payload.cohorts[1]?.label??"B"} — D${checkpoint}`,request:state.payload.request,resultHash:state.payload.result_hash}}/></div><div className="advanced-result-meta"><span>تداخل: <b className="num">{state.payload.overlap_n.toLocaleString("en-US")}</b></span><span>الحساب: <b className="num">{new Date(state.payload.evaluated_at).toLocaleString("en-US")}</b></span></div><p className="notice">تُستبعد الفترة <span className="num">2026-04-01</span> إلى ما قبل <span className="num">2026-06-01</span> فقط، إضافة إلى المواد المؤرشفة.</p><ComparisonResultTable rows={state.payload.metrics} selectedMetric={selectedMetric} onSelectMetric={setSelectedMetric}/></section><section className="card stack"><h2>{advancedMetricLabels[selectedMetric]}</h2>{advancedReelsWarning(selectedMetric,state.payload.evidence)?<p className="notice">توجد مواد ريلز ينقصها مكوّن مطلوب؛ يظهر ذلك ضمن N وأسباب الاستبعاد.</p>:null}<ComparisonChart rows={chartRows} metricLabel={advancedMetricLabels[selectedMetric]}/></section>{timeline.length?<section className="card stack"><MetricLineChart title={`الخط الزمني الشهري — ${advancedMetricLabels[selectedMetric]}`} sourceTime={state.payload.source_bounds.last} series={series}/><div className="advanced-timeline-n">{timeline.map(point=><span key={`${point.month}:${point.cohort}`}>{point.month} · {point.cohort}: <b className="num">N={point.n}</b></span>)}</div></section>:null}<ComparisonEvidence payload={state.payload} metric={selectedMetric} currentUserId={currentUserId} roles={roles} teamMembers={teamMembers} teamMembersLoadError={teamMembersLoadError}/><p className="muted advanced-source-time">المصدر: <span className="num">{state.payload.source_bounds.first??"—"}</span> — <span className="num">{state.payload.source_bounds.last??"—"}</span></p></>:null}</div>;
}
