import type { AdvancedCohort, AdvancedMediaType, AdvancedParticipantRole } from "@/lib/advanced-comparison";
type Option={key:string;name:string};
export type AdvancedComparisonOptions={track:Option[];partner:Option[];idea_type:Option[];media_type:Option[];person:Option[]};
function toggleNumber(values:number[],value:number){return values.includes(value)?values.filter(entry=>entry!==value):values.length<20?[...values,value]:values;}
function toggleMedia(values:AdvancedMediaType[],value:AdvancedMediaType){return values.includes(value)?values.filter(entry=>entry!==value):values.length<20?[...values,value]:values;}
export function CohortEditor({cohort,options,onChange}:{cohort:AdvancedCohort;options:AdvancedComparisonOptions;onChange:(next:AdvancedCohort)=>void}){
  const numeric=(field:"track_ids"|"partner_ids"|"idea_type_ids",value:string)=>onChange({...cohort,[field]:toggleNumber(cohort[field],Number(value))});
  function person(id:string){const existing=cohort.participants.find(entry=>entry.person_id===id);onChange({...cohort,participants:existing?cohort.participants.filter(entry=>entry.person_id!==id):[...cohort.participants,{person_id:id,role:null}]});}
  function role(id:string,value:string){onChange({...cohort,participants:cohort.participants.map(entry=>entry.person_id===id?{...entry,role:value?value as AdvancedParticipantRole:null}:entry)});}
  const group=(title:string,items:Option[],field:"track_ids"|"partner_ids"|"idea_type_ids")=><details><summary>{title} <span className="num">({cohort[field].length})</span></summary><div className="comparison-options">{items.map(item=><label className="comparison-option" key={item.key}><input type="checkbox" checked={cohort[field].includes(Number(item.key))} onChange={()=>numeric(field,item.key)}/><span>{item.name}</span></label>)}</div></details>;
  return <section className="card stack advanced-cohort"><div className="advanced-cohort-title"><b className="num">{cohort.key}</b><input className="input" maxLength={80} aria-label={`اسم المجموعة ${cohort.key}`} value={cohort.label} onChange={event=>onChange({...cohort,label:event.target.value})}/></div><div className="form-grid"><label className="field">من<input className="input num" type="date" required value={cohort.range.start} onChange={event=>onChange({...cohort,range:{...cohort.range,start:event.target.value}})}/></label><label className="field">إلى<input className="input num" type="date" required value={cohort.range.end} onChange={event=>onChange({...cohort,range:{...cohort.range,end:event.target.value}})}/></label></div>
    {group("المسارات",options.track,"track_ids")}{group("الشركاء",options.partner,"partner_ids")}{group("أنواع الفكرة",options.idea_type,"idea_type_ids")}
    <details><summary>أنواع المحتوى <span className="num">({cohort.media_types.length})</span></summary><div className="comparison-options">{options.media_type.map(item=><label className="comparison-option" key={item.key}><input type="checkbox" checked={cohort.media_types.includes(item.key as AdvancedMediaType)} onChange={()=>onChange({...cohort,media_types:toggleMedia(cohort.media_types,item.key as AdvancedMediaType)})}/><span>{item.name}</span></label>)}</div></details>
    <details><summary>الأشخاص والأدوار <span className="num">({cohort.participants.length})</span></summary><div className="advanced-people-options">{options.person.map(item=>{const selected=cohort.participants.find(entry=>entry.person_id===item.key);return <div className="advanced-person-option" key={item.key}><label className="comparison-option"><input type="checkbox" checked={Boolean(selected)} onChange={()=>person(item.key)}/><span>{item.name}</span></label>{selected?<select className="input" aria-label={`دور ${item.name}`} value={selected.role??""} onChange={event=>role(item.key,event.target.value)}><option value="">كل أدواره</option><option value="writer">كاتب</option><option value="reviewer">مراجع</option><option value="producer">منتج</option></select>:null}</div>;})}</div></details>
  </section>;
}
